export const MedNames = {
    Aspen : 0,
    Mimulus : 0,
    CherryPlum : 0,
    RedchestNut : 0,
    RockRose : 0,
    Cerato : 0,
    Scleranthu : 0,
    WildOat : 0,
    Larch : 0,
    Hornbeam : 0,
    Clemantis : 0,
    HoneySuckle : 0,
    WildRose : 0,
    WhiteChestnut : 0,
    ChestNutBud : 0,
    Olive : 0,
    WaterViolet : 0,
    Impatiens : 0,
    Heather : 0,
    Agrimony : 0,
    Centaury : 0,
    Walnut : 0,
    Holly : 0,
    Pine : 0,
    Elm : 0,
    StarOfBeth : 0,
    SweetChestNut : 0,
    Gorse : 0,
    Mustard : 0,
    Gentian : 0,
    Oak : 0,
    Willow : 0,
    CrabApple : 0,
    Chicory : 0,
    Beech : 0,
    Vervain : 0,
    RockWater : 0,
    Vine : 0
}

export const types = {
    Fear : 0,
    Lonliness : 0,
    Uncertainty : 0,
    Sensitivity : 0,
    InsufficientInterestInPresent : 0,
    DespondencyAndDespair : 0,
    OverCare : 0

}